{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreName }}
  labels:
    {{- include "ai-inference.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecret.aws.region | quote }}
{{- end }}
