{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ai-inference.fullname" . }}
  labels:
    {{- include "ai-inference.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ai-inference.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.serviceMonitor.path | quote }}
      interval: {{ .Values.monitoring.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout | quote }}
{{- end }}
