{{- if .Values.serviceAccount.create }}
{{- $serviceAccountAnnotations := dict }}
{{- range $key, $value := .Values.serviceAccount.annotations }}
{{- if $value }}
{{- $_ := set $serviceAccountAnnotations $key $value }}
{{- end }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-inference.serviceAccountName" . }}
  labels:
    {{- include "ai-inference.labels" . | nindent 4 }}
  {{- with $serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
